# Copyright 2024 Colin Marc <hi@colinmarc.com>
#
# SPDX-License-Identifier: MIT
#
# This file specifies the configuration defaults for the magic mirror server. If
# a line is commented out, the default is to leave the value unset (and the
# setting is not required, unless stated otherwise).
#
# To determine the final config, the server merges the values in this file with
# the configuration file (by default, /etc/magic-mirror/mmserver.toml).
#
# All configuration files may be json instead of toml.

# If set, this special setting instructs the server to load additional application
# configurations from the given files or directories. Each file (or file in in
# the directories) should be named using the scheme `<NAME>.toml` or
# `<NAME>.json`, where `<NAME>` is the name of the application, following the
# rules outlined below. The contents should be identical to the configuration
# for an individual app.
# include_apps = ["/etc/magic-mirror/apps.d"]

# *** Server Settings ***
#
# Options for configuring the server.

[server]

# Where the server should listen for incoming connections. IPv6 addresses are
# supported. Use 0.0.0.0 or [::] to listen on all available interfaces.
bind = "localhost:9599"

# If set, `bind` will be ignored, and the server will instead listen for
# incoming connections on the socket specified by the LISTEN_FDS environment
# variable. See the systemd documentation on "socket activation", here:
# https://www.freedesktop.org/software/systemd/man/latest/systemd.socket.html
bind_systemd = false

# Used for TLS. Both are required unless the host portion of the bind address
# resolves to a private address (as defined by RFCs 1918, 4193, and 6598) or
# otherwise not routable, for example 127.0.0.1, 192.168.24.25, or
# fd12:3456:789a:1::1. 
# tls_key = "/path/to/tls.key"
# tls_cert = "/path/to/tls.cert"

# The number of threads to spawn for handling incoming requests.
worker_threads = 8

# The maximum number of concurrent connections the server will accept. Use `inf`
# to specify no limit.
max_connections = 1

# *** Configured Applications *** 
#
# Each application you want to stream must be configured in advance. An example
# application configuration follows. Note that unlike the rest of this file,
# this is not included in the default configuation.

# App names must be unique and only contain characters in the set [a-z0-9-_].
#
# Applications can be configured in a central file or as individual files. See
# the documentation for `app_dirs` above for more information. At least one application
# must be specified.

[apps.steam-big-picture-example]
# The command to run to start the application.
command = ["steam", "-gamepadui"]

# Environment variables to set on the application.
environment = { "FOO" = "bar" }

# Enable XWayland support for this application. This is required for any
# application that are built for the legacy X11 windowing system, such as Steam.
xwayland = true

# Force the app to run at 1x. This is useful for applications where you know in
# advance they don't support any UI scaling, for example any application run
# through XWayland. This setting will ensure that the app always renders at the
# full session resolution, but may result in small font sizes or other UI
# elements.
force_1x_scale = false

# *** Default App Settings *** 
#
# This section can be used to set global defaults for all apps (see the [[apps]]
# section below). Any setting here can be overriden in the configuration for
# each individual app.

[default_app_settings]
xwayland = true
force_1x_scale = false
