base_url = "https://colinmarc.github.io/magic-mirror"
theme = "anemone"
compile_sass = false
build_search_index = false

[markdown]
highlight_code = true

[extra]
twitter_card = false
header_nav = [
  { url = "https://colinmarc.github.io/magic-mirror", name_en = "/home/"},
  { url = "https://github.com/colinmarc/magic-mirror", name_en = "/github/"},
  { url = "https://discord.gg/v22G644DzS", name_en = "/discord/"},
]
