on:
  push:
    tags:
      - 'mmserver-v*.*.*'

name: Release mmserver
jobs:
  create_release:
    name: Create mmserver release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-gnu

      - name: install deps
        run: sudo apt install nasm cmake protobuf-compiler libxkbcommon-dev

      - name: install slang
        run: |
          mkdir $RUNNER_TEMP/slang
          slang_url=$( gh api https://api.github.com/repos/shader-slang/slang/releases/latest |\
            jq -r '.assets[] | .browser_download_url' | grep linux-x86_64.tar.gz )
          (cd $RUNNER_TEMP/slang && curl -o - -fsSL "$slang_url" | tar zxv)
          echo "SLANG_DIR=$RUNNER_TEMP/slang" >> "$GITHUB_ENV"
          echo "LD_LIBRARY_PATH=$(dirname $(find $RUNNER_TEMP/slang -name libslang.*))" >> "$GITHUB_ENV"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v4
      - uses: swatinem/rust-cache@v2
        with:
          workspaces: |
            mm-server
            mm-client
            mm-protocol

      - name: cargo build
        run: (cd mm-server && cargo build --bin mmserver --release --target x86_64-unknown-linux-gnu)
      - name: create release tarball
        run: |-
          mkdir "${RUNNER_TEMP}/${GITHUB_REF_NAME}"
          cp -r mm-server/target/x86_64-unknown-linux-gnu/release/mmserver README.md mmserver.default.toml \
            "${RUNNER_TEMP}/${GITHUB_REF_NAME}"
          cp LICENSES/BUSL-1.1.txt "${RUNNER_TEMP}/${GITHUB_REF_NAME}/LICENSE.txt"
          tar -C "${RUNNER_TEMP}" --numeric-owner -cvzf "${GITHUB_REF_NAME}-linux-amd64.tar.gz" "$GITHUB_REF_NAME"

      - name: install git-cliff
        run: cargo install git-cliff
      - name: generate release notes
        run: |-
          echo "# Server version ${GITHUB_REF_NAME/mmserver-v/}" >> release-notes.txt
          git cliff -c .github/workflows/cliff.toml \
            --include-path "mm-server/**/*" \
            --tag-pattern "server" \
            --tag "$GITHUB_REF_NAME" --latest | tail -n +2 | tee -a release-notes.txt


      - name: create release
        uses: softprops/action-gh-release@v2
        with:
          body_path: release-notes.txt
          files: "mmserver-*.tar.gz"



