on:
  push:
    branches: [main, test-ci]
  pull_request:
    branches: [main]
name: Tests
jobs:
  tests:
    name: Server Tests
    runs-on: ubuntu-latest
    steps:
      - uses: dtolnay/rust-toolchain@stable
      - name: install deps
        run: |
          sudo apt install \
            nasm cmake protobuf-compiler libxkbcommon-dev

      - uses: actions/checkout@v4
      - uses: swatinem/rust-cache@v2
        with:
          workspaces: |
            mm-server
            mm-protocol

      - name: server tests
        run: (cd mm-server && cargo test)
      - name: protocol tests
        run: (cd mm-protocol && cargo test)
      - name: server cargo clippy
        run: (cd mm-server && cargo clippy)
      - name: protocol cargo clippy
        run: (cd mm-protocol && cargo clippy)


